rim_nestle:
    resource: "@RimNestleBundle/Controller/"
    type:     annotation
    prefix:   /

rim_korona:
    resource: "@RimKoronaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
