<?php
namespace Rim\PlayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{

    public function findOneMaxPriority()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT l.name FROM RimPlayerBundle:Link l ORDER BY l.priority DESC')
            ->setMaxResults(1)
            ->getSingleScalarResult();
//         $qb = $this->createQueryBuilder('l')
//             ->orderBy('l.priority', 'DESC')
//             ->setMaxResults(1);
//         $query = $qb->getQuery();
//         return $query->getResult();
    }
}
