<?php

namespace Rim\NestleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrizRepository extends EntityRepository
{
}
